### PR TITLE
Made CURL working

### PR DESCRIPTION
**Pull request by ank91**
Hi,
I could not get the ```examples\basics.php``` working, i was getting ```null``` in response always. 
So i inherited some code from [here](https://github.com/ZEALi/Google-Analytics-API-PHP).
And now it working fine.

I am planing to use this library in one of my project, i found yours repo well maintained among all.

Thanks

### CODE REVIEW

**Comment by timgws** [comment]
Hi @anke91,

Thanks for this PR.

The cURL code does infact work for me. Just as a side note, `CURLOPT_SSL_VERIFYPEER` and `CURLOPT_SSL_VERIFYHOST` should not be set to false. This is very important.

Otherwise, someone could do a MITM attack against your host, and return results via SSL that will not get noticed correctly by the Goole Analytics API code.

What OS are you running? Is your SSL config correct? Are you running cURL with (or, does your operating system have) the most correct & up to date root certificates?

See:

* https://labs.bitpay.com/t/how-to-update-the-root-ca-cert-bundle-on-your-webserver-if-you-are-getting-curl-ssl-errors/315
* http://php.net/manual/en/function.curl-setopt.php#110457
* http://stackoverflow.com/questions/2694787/how-can-i-set-curlopt-cainfo-globally-for-php-on-windows

**Comment by ank91** [comment]
Hi @timgws , thanks for quick reply.

You are right, it is a platform specific issue.
I was on Windows 7 with WAMP 2.5 (php v5.5.12) Installed.
Just tested it on Ubuntu 14.04 (php v5.6) and the original library (yours) worked without problem.

I will look into why it is not working on Windows platform (cainfo).
However i am not a cURL expert.

So you can close this PR without merging and enjoy your coffee.
Thanks again for your time and this awesome library.

**Comment by timgws** [comment]
@ank91 I have updated the cURL code with the additional options, however, with gzip compression.

**Comment by ank91** [comment]
:thumbsup: great, thanks,

The good news is that i made it working on Windows 7 machine by install the certificate.

**Pull request closed without merging**
